@BasketAPI_HostAddress = https://localhost:7083/basket/


GET {{BasketAPI_HostAddress}}xxx
Accept: application/json

###

POST {{BasketAPI_HostAddress}}
Content-Type: application/json
{
    "UserName": "xxx",
    "Items": [
        {
        "Quantity": 2,
        "Color": "Red",
        "Price": 0,
        "ProductId": 1,
        "ProductName": "Solar Powered Flashlight"
        },
        {
        "Quantity": 1,
        "Color": "Blue",
        "Price": 0,
        "ProductId": 2,
        "ProductName": "Hiking Poles"
        }
    ]
}

###
DELETE {{BasketAPI_HostAddress}}xxx
Content-Type: application/json